config/routes.rb
Rails.application.routes.draw do
  root to: 'system#index'
  # session login/logout routes
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :login_post
  get '/logout' => 'sessions#destroy', as: :logout
  # registration routes
  get '/register' => 'user#new', as: :register
  post '/user' => 'user#create', as: :user_create
  get '/user' => 'user#new'
  get '/user/:token/confirm_email' => 'user#confirm_email', as: :confirm_email_user
  # password reset routes
  get '/user/reset' => 'password#new', as: :reset
  post '/user/reset' => 'password#reset', as: :reset_post
  get '/user/:token/new_password' => 'password#edit', as: :new_password_request
  put '/user/new_password.:token' => 'password#update', as: :update_password
  
  # after login routes
  get '/cat' => 'cat#show', as: :cat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token

  has_secure_password

  validates :name, presence: true
  validates :email, uniqueness: { case_sensitive: false, message: 'User already registered' }, presence: true
  # TODO: Validate email by sending an actual email to the user

  validate :password_complexity

  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!
  end

  def reset_token
    self.reset_password_token = SecureRandom.urlsafe_base64.to_s
    self.reset_password_token_expires_at = DateTime.now.advance(days: 1)
    save
  end

  def deactivate_reset_password
    self.reset_password_token = nil
    self.reset_password_token_expires_at = nil
    self.save
  end

  private

    def password_complexity
      if password.present? && !password.match(/\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+\z/)
        errors.add :password, 'must include at least one lowercase letter, one uppercase letter, and one digit'
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    begin
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      end
    rescue
      flash[:danger] = 'Invalid session'
      @current_user = nil
    end
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/cat_controller.rb
class CatController < ApplicationController
  before_action :authorize
  def show
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def new
  end

  def reset
    user = User.find_by(email: params[:email])
    if user
      user.reset_token
      UserMailer.reset_password(user).deliver
    end
    redirect_to root_path
  end
  
  # reset password directed here from user reset password email
  def edit
    now = DateTime.now
    @token = params[:token]
    @user = User.find_by(reset_password_token: @token)
    # if there is no such token or it has expired then go back to root
    if @user.blank? || (@user.reset_password_token_expires_at < now)
      flash[:danger] = 'Apologies, but it seems that this reset url is invalid. Please request a new password reset'
      redirect_to root_path
    end
  end

  def update
    @user = User.find_by(reset_password_token: params[:token])
    @user = User.update(@user.id, reset_params)
    if @user.save
      @user.deactivate_reset_password
      flash[:success] = 'You have successfully reset your password. Please login'
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  private

    def reset_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    isUserValid(user)
  end

  def destroy
    # session[:user_id] = nil
    reset_session
    redirect_to root_path
  end

  private
    def invalidLoginResponse
      flash[:danger] = 'Invalid username and/or password'
      redirect_to login_path
    end
    
    def isUserValid(user)
      if user
        isUserAuthenticated(user)
      else
        invalidLoginResponse
      end
    end
    
    def isUserAuthenticated(user)
      now = DateTime.now.utc.to_s(:db)
      if user.authenticate(params[:password])
        isUserConfirmed(user, now)
      else
        user.last_failed_login = now
        user.failed_login_count += 1

        user.save
        invalidLoginResponse
      end
    end
    
    def isUserConfirmed(user, now)
      if user.email_confirmed
        user.last_login = now
        user.save

        session[:user_id] = user.id
        redirect_to cat_path
      else
        flash[:warning] = 'Your email address has not been confirmed. Please confirm your email address clicking the link in the email we sent you'
        redirect_to root_path
      end
    end
end

app/controllers/system_controller.rb
class SystemController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = 'Please confirm your email address by clicking the link int the email we just sent you'
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def confirm_email
    user = User.find_by(confirm_token: params[:token])
    if user
      user.email_activate
      flash[:success] = 'Your account has been confirmed, please login to continue'
      redirect_to login_path
    else
      flash[:danger] = 'Apologies, but we can not confirm you account'
      redirect_to root_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/system_helper.rb
module SystemHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cat/show.html.erb
<p><%= image_tag('giphy.gif', width: '45%', class: 'img-rounded') %></p>
<%= render "partials/login_controls" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication demo by Fadi Asfour</title>
    <%= csrf_meta_tags %>
    <meta name="robots" content="noindex, nofollow">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
         <div class="header clearfix">
           <nav>
                     <ul class="nav nav-pills pull-right">
                       <li role="presentation"><%= link_to 'Home', root_url %></li>
                       <li role="presentation"><a href="#">About</a></li>
                       <li role="presentation"><a href="#">Contact</a></li>
                     </ul>
                   </nav>
           <h3 class="text-muted">Authenticate</h3>
         </div>

         <div class="jumbotron">
           <% flash.each do |key, value| %>
             <div class="alert alert-<%= key %>" role='alert'><%= value %></div>
           <% end %>
           
           <%= yield %>
           
         </div>

         <footer class="footer">
           <p>&copy; Fadi Asfour 2016</p>
         </footer>

       </div>

  </body>
</html>

app/views/partials/_form_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_details">
    <div class='alert alert-warning text-left'>
      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/partials/_login_controls.html.erb
<% if current_user %>
  <p class='lead'>Signed in as <%= current_user.name %> | <%= link_to 'Logout', logout_url %></p>
<% else %>
  <p class="lead">Go ahead, login!</p>
  <p><%= link_to 'LOGIN', login_url, class: 'btn btn-lg btn-success', role: 'button' %></p>
  <p><%= link_to 'Signup', register_url %></p>
<% end %>

app/views/password/edit.html.erb
<h1>Reset Password</h1>
<p class='lead'>Please fill in the following information</p>
<%= form_for @user, url: update_password_url(@token), html: { method: :put, class: 'form-horizontal'}  do |form| %>
  <%= render 'partials/form_error_messages', object: form.object %>
  <div class='form-group'>
    <div class='input-group'>
      <span class='input-group-addon' id='username_addon'>
        <span class='glyphicon glyphicon-lock'></span>
      </span>
      <%= form.password_field :password , class: 'form-control', placeholder: 'New Password' %>
    </div>
  </div>
  <div class='form-group'>
    <div class='input-group'>
      <span class='input-group-addon' id='username_addon'>
        <span class='glyphicon glyphicon-lock'></span>
      </span>
      <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm your password' %>
    </div>
  </div>
  <%= form.submit 'Register' , class: 'btn btn-lg btn-primary'%>
<% end %>

app/views/password/new.html.erb
<p class='lead'>Request reset password</p>
<%= form_tag reset_post_url, class: 'form-inline' do %>
  <div class="form-group">
    <div class='input-group'>
      <span class='input-group-addon' id='username_addon'><span class='glyphicon glyphicon-user'></span></span>
      <%= text_field_tag :email, nil, class: 'form-control', placeholder: 'Email address' %>
      <span class="input-group-btn">
        <%= submit_tag 'Reset' , class: 'btn btn-primary', id: 'inline-btn' %>
      </span>
    </div>
  </div>
<% end %>

app/views/system/index.html.erb
<h1 class="display-3">DEMO AUTHENTICATION</h1>
<%= render "partials/login_controls" %>

app/views/user/new.html.erb
<h1>New User</h1>
<p class='lead'>Please fill in the following information</p>
<%= form_for @user, url: user_create_url, html: {class: 'form-horizontal'}  do |form| %>
  <%= render 'partials/form_error_messages', object: form.object %>
  <div class='form-group'>
  <div class='input-group'>
    <span class='input-group-addon' id='username_addon'><span class='glyphicon glyphicon-user'></span></span>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Full Name', 'aria-describedby': 'username_addon' %>
  </div></div>
  <div class='form-group'>
    <div class='input-group'>
      <span class='input-group-addon' id='username_addon'>@</span>
    <%= form.text_field :email, class: 'form-control', placeholder: 'Email address' %>
  </div></div>
  <div class='form-group'>
    <div class='input-group'>
      <span class='input-group-addon' id='username_addon'><span class='glyphicon glyphicon-lock'></span></span>
    <%= form.password_field :password , class: 'form-control', placeholder: 'Password' %>
  </div></div>
  <div class='form-group'>
    <div class='input-group'>
      <span class='input-group-addon' id='username_addon'><span class='glyphicon glyphicon-lock'></span></span>
    <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm your password' %>
  </div></div>  
  <%= form.submit 'Register' , class: 'btn btn-lg btn-primary'%>
<% end %>